/*:
# Deferred Protocols

A protocol can have the actual types of properties and method arguments/results be determined by the implementor
*/
// Example from standard library
protocol Equatable {
    func ==(lhs:Self, rhs:Self) -> Bool
}

// Example from standard library
public protocol GeneratorType {
    /// The type of element generated by `self`.
    typealias Element

    mutating func next() -> Self.Element?
}

//: [⬅ Previous](@previous) || [Next ➡](@next)